"""
Simple JS concatenation tool for the project.
Usage (PowerShell):
    python CodeGenerator/scripts/tools/combine_js.py CodeGenerator/scripts "CodeGenerator/functions.js" "CodeGenerator/ModuleFunctions.js" -o CodeGenerator/functions.combined.js
Or run without args to use a sensible default list.
"""
import sys
from pathlib import Path
import argparse

def read_file(path: Path) -> str:
    return path.read_text(encoding='utf-8')


def write_file(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding='utf-8')


def main():
    parser = argparse.ArgumentParser(description='Concatenate JS files into one output file')
    parser.add_argument('src_dir', nargs='?', default='CodeGenerator/scripts', help='Directory with script parts')
    parser.add_argument('extra_files', nargs='*', help='Other files to append after the scripts (e.g., functions.js, ModuleFunctions.js)')
    parser.add_argument('-o', '--out', default='CodeGenerator/functions.combined.js', help='Output file')
    args = parser.parse_args()

    src_dir = Path(args.src_dir)
    out_path = Path(args.out)

    # Default order: all files in scripts/ in alphabetical order, then extras
    files = []
    if src_dir.exists() and src_dir.is_dir():
        for p in sorted(src_dir.glob('*.js')):
            files.append(p)
    for ef in args.extra_files:
        files.append(Path(ef))

    if not files:
        print('No files found to combine. Exiting.')
        sys.exit(1)

    parts = []
    parts.append('// Combined functions file generated by CodeGenerator/scripts/tools/combine_js.py')
    parts.append('// Files:')
    for f in files:
        parts.append(f'// - {f}')
    parts.append('\n')

    for f in files:
        if not f.exists():
            print(f'Warning: {f} not found, skipping')
            continue
        content = read_file(f)
        parts.append(f'// ---- START {f} ----')
        parts.append(content)
        parts.append(f'// ---- END {f} ----\n')

    final = '\n'.join(parts)
    write_file(out_path, final)
    print(f'Wrote combined file to {out_path.resolve()}')

if __name__ == '__main__':
    main()
